/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SocialShareStencil {
    /**
    * Is the list expanded or not
    */
    'show': boolean;
  }
  interface SocialShareStencilAttributes extends StencilHTMLAttributes {
    /**
    * The event triggerd when an item is clicked
    */
    'onShare-to'?: (event: CustomEvent) => void;
    /**
    * Is the list expanded or not
    */
    'show'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SocialShareStencil': Components.SocialShareStencil;
  }

  interface StencilIntrinsicElements {
    'social-share-stencil': Components.SocialShareStencilAttributes;
  }


  interface HTMLSocialShareStencilElement extends Components.SocialShareStencil, HTMLStencilElement {}
  var HTMLSocialShareStencilElement: {
    prototype: HTMLSocialShareStencilElement;
    new (): HTMLSocialShareStencilElement;
  };

  interface HTMLElementTagNameMap {
    'social-share-stencil': HTMLSocialShareStencilElement
  }

  interface ElementTagNameMap {
    'social-share-stencil': HTMLSocialShareStencilElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
